[package]
name = "rust-gpt2"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.18.0", features = ["dataset", "train", "autodiff", "candle" ] }
burn-import = "0.18.0"
rand = "0.9.2"
regex = "1.11.1"
tiktoken-rs = "0.7.0"
