[package]
name = "llm-from-scratch"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.18.0", features = ["dataset", "train", "autodiff", "candle" ] }
regex = "1.11.1"
tiktoken-rs = "0.7.0"
